export const categoryOrder = [
  "생면파스타",
  "피자 · 리조또 · 메인",
  "에피타이저 · 디저트",
  "음료",
];

export const menuData = [
  // 생면파스타
{
  id: "pasta-1",
  category: "생면파스타",
  name: "마늘새우 스파게티",
  description: "구운 마늘 페이스트의 깊은 풍미를 살린 매콤한 파스타",
  price: 18000,
  image: "/images/menu/Shrimp-Garlic-Spaghetti.png",
  badges: ["🌶"],
  featured: false,
  order: 2,
},
  {
    id: "pasta-2",
    category: "생면파스타",
    name: "토마토 스파게티",
    description: "산뜻한 토마토 소스에 스트라차텔라 치즈를 더한 스파게티",
    price: 16000,
    image: "/images/menu/tomato-spaghetti.png",
    badges: [],
    featured: false,
    order: 4,
  },
  {
    id: "pasta-3",
    category: "생면파스타",
    name: "버섯크림 리가토니",
    description: "진한 버섯 풍미와 고소한 크림의 리가토니",
    price: 17000,
    image: "/images/menu/Mushroom-Cream-Rigatoni.png",
    badges: ["인기"],
    featured: true,
    order: 1,
  },
  {
    id: "pasta-4",
    category: "생면파스타",
    name: "비스크 새우 딸리아뗄레",
    description: "새우 비스크의 깊은 풍미를 살린 딸리아뗄레",
    price: 23000,
    image: "/images/menu/Bisque shrimp tagliatelle.png",
    badges: ["시그니처"],
    featured: false,
    order: 3,
  },
  {
    id: "pasta-5",
    category: "생면파스타",
    name: "구운당근 크림 뇨끼",
    description: "부드러운 당근 풍미와 피스타치오의 고소함",
    price: 18000,
    image: "/images/menu/Roasted Carrot Cream Gnocchi.png",
    badges: [],
    featured: false,
    order: 7,
  },
  {
    id: "pasta-6",
    category: "생면파스타",
    name: "포르치니 버섯 뇨끼",
    description: "포르치니 향을 살린 진한 버섯 뇨끼",
    price: 21000,
    image: "/images/menu/Porcini gnocchi.png",
    badges: [],
    featured: false,
    order: 8,
  },
  {
    id: "pasta-7",
    category: "생면파스타",
    name: "화이트라구 딸리아뗄레",
    description: "부드럽고 깊은 풍미의 화이트라구 딸리아뗄레",
    price: 19000,
    image: "/images/menu/White ragu tagliatelle.png",
    badges: ["인기"],
    featured: false,
    order: 5,
  },
  {
  id: "pasta-8",
  category: "생면파스타",
  name: "바질페스토 스파게티",
  description: "바질의 향긋함과 고소함이 살아있는 스파게티",
  price: 18000,
  image: "/images/menu/Basil Pesto Spaghetti.png",
  badges: [],
  featured: false,
  order: 6,
},

  // 피자 · 리조또 · 메인
  {
    id: "main-1",
    category: "피자 · 리조또 · 메인",
    name: "채끝등심 버섯 리조또",
    description: "채끝등심과 버섯의 풍미를 담은 리조또",
    price: 26000,
    image: "/images/menu/Sirloin mushroom risotto.png",
    badges: [],
    featured: false,
    order: 1,
  },
  {
    id: "main-2",
    category: "피자 · 리조또 · 메인",
    name: "먹물관자 리조또",
    description: "먹물의 감칠맛과 관자의 풍미를 살린 리조또",
    price: 20000,
    image: "/images/menu/Squid-ink-scallop-risotto.png",
    badges: [],
    featured: false,
    order: 2,
  },
  {
    id: "main-3",
    category: "피자 · 리조또 · 메인",
    name: "가리비관자피자",
    description: "관자의 풍미를 살린 꼬모 대표 피자",
    price: 21000,
    image: "/images/menu/Scallop pizza.png",
    badges: ["시그니처"],
    featured: true,
    order: 3,
  },
  {
    id: "main-4",
    category: "피자 · 리조또 · 메인",
    name: "리코타 고르곤졸라 피자",
    description: "리코타의 부드러움과 고르곤졸라의 풍미",
    price: 17000,
    image: "/images/menu/Ricotta-Gorgonzola-pizza.png",
    badges: ["인기"],
    featured: false,
    order: 4,
  },
  {
    id: "main-5",
    category: "피자 · 리조또 · 메인",
    name: "마르게리따 피자",
    description: "토마토, 치즈, 바질의 클래식 피자",
    price: 15000,
    image: "/images/menu/Margherita.png",
    badges: [],
    featured: false,
    order: 5,
  },
  {
    id: "main-6",
    category: "피자 · 리조또 · 메인",
    name: "채끝등심 250g",
    description: "담백하게 구운 채끝등심 스테이크",
    price: 47000,
    image: "/images/menu/Striploin Steak.png",
    badges: ["메인"],
    featured: false,
    order: 6,
  },

  // 에피타이저 · 디저트
{
  id: "side-1",
  category: "에피타이저 · 디저트",
  name: "부라타치즈",
  description: "바질페스토와 절인 토마토, 무화과, 루꼴라를 곁들인 부라타치즈",
  price: 17000,
  image: "/images/menu/burata-cheese.jpg",
  badges: ["추천"],
  featured: false,
  order: 1,
},
{
  id: "side-2",
  category: "에피타이저 · 디저트",
  name: "리코타치즈샐러드",
  description: "신선한 채소와 수제 리코타치즈, 파스닙칩을 곁들인 샐러드",
  price: 15000,
  image: "/images/menu/Ricotta cheese salad.png",
  badges: ["시그니처"],
  featured: false,
  order: 2,
},
{
  id: "side-3",
  category: "에피타이저 · 디저트",
  name: "트러플감자튀김",
  description: "트러플 향을 더한 감자튀김",
  price: 10000,
  image: "/images/menu/Truffle fries.png",
  badges: [],
  featured: false,
  order: 3,
},
{
  id: "side-4",
  category: "에피타이저 · 디저트",
  name: "빵추가 3피스",
  description: "소스와 함께 곁들이기 좋은 빵 추가",
  price: 5000,
  image: "",
  badges: [],
  featured: false,
  order: 4,
},
{
  id: "side-5",
  category: "에피타이저 · 디저트",
  name: "오늘의 디저트",
  description: "당일 준비된 디저트",
  price: 5000,
  image: "",
  badges: ["추천"],
  featured: false,
  order: 5,
},
   // 음료
  {
    id: "drink-1",
    category: "음료",
    section: "ade",
    name: "수제청 에이드",
    description: "레몬 / 자몽 / 패션오렌지",
    price: 5500,
    image: "/images/menu/Ade drinks.png",
    badges: [],
    order: 1,
  },
  {
    id: "drink-2",
    category: "음료",
    section: "basic",
    name: "산펠레그리노 탄산수",
    description: "500ml",
    price: 7000,
    tag: "SPARKLING WATER",
    image: "",
    badges: [],
    order: 2,
  },
  {
    id: "drink-3",
    category: "음료",
    section: "basic",
    name: "콜라 / 스프라이트/ 제로콜라",
    description: "콜라 / 스프라이트 / 제로콜라",
    price: 2000,
    tag: "SOFT DRINKS",
    image: "",
    badges: [],
    order: 3,
  },
  {
    id: "drink-4",
    category: "음료",
    section: "basic",
    name: "아메리카노",
    description: "hot / ice",
    price: 4000,
    tag: "COFFEE",
    image: "",
    badges: [],
    order: 4,
  },
{
  id: "drink-5",
  category: "음료",
  section: "tea",
  name: "레몬 스카이",
  description: "산뜻하고 가볍게 즐기기 좋은 허브티 · hot / ice",
  price: 3000,
  tag: "TEA",
  image: "",
  badges: [],
  order: 5,
},
{
  id: "drink-6",
  category: "음료",
  section: "tea",
  name: "실버라임 블라썸",
  description: "은은한 꽃향과 산뜻한 시트러스 향의 티 · hot / ice",
  price: 3000,
  tag: "TEA",
  image: "",
  badges: [],
  order: 6,
},
{
  id: "drink-7",
  category: "음료",
  section: "tea",
  name: "루이보스 바닐라",
  description: "부드럽고 포근한 바닐라 향의 루이보스 티 · hot / ice",
  price: 3000,
  tag: "TEA",
  image: "",
  badges: [],
  order: 7,
},
  {
    id: "drink-8",
    category: "음료",
    section: "kids",
    name: "어린이주스",
    description: "뽀로로 밀크맛 / 오렌지주스",
    price: 2000,
    tag: "KIDS",
    image: "",
    badges: [],
    order: 8,
  },

  // 스파클링 와인
  {
    id: "sparkling-1",
    category: "음료",
    section: "sparklingWine",
    name: "벨 그로브 브뤼",
    englishName: "Belle Grove Brut [스페인]",
    price: 30000,
    order: 9,
  },

  // 화이트 와인
  {
    id: "white-1",
    category: "음료",
    section: "whiteWine",
    name: "쇼 앤 스미스 리슬링",
    englishName: "Shaw and Smith Riesling",
    price: 70000,
    order: 10,
  },
  {
    id: "white-2",
    category: "음료",
    section: "whiteWine",
    name: "캔달 잭슨 빈트너리 리저브 소비뇽 블랑",
    englishName: "Kendall-Jackson, Vintner's Reserve Sauvignon Blanc",
    price: 50000,
    order: 11,
  },
  {
    id: "white-3",
    category: "음료",
    section: "whiteWine",
    name: "제나토 소아베 클라시코",
    englishName: "Zenato Soave Classico",
    price: 40000,
    order: 12,
  },

  // 레드 와인
  {
    id: "red-1",
    category: "음료",
    section: "redWine",
    name: "빌라 안티노리 로쏘",
    englishName: "Villa Antinori Toscana Rosso",
    price: 60000,
    order: 13,
  },
  {
    id: "red-2",
    category: "음료",
    section: "redWine",
    name: "스테마리 네로 다볼라",
    englishName: "Stemmari Nero d'Avola",
    price: 55000,
    order: 14,
  },
  {
    id: "red-3",
    category: "음료",
    section: "redWine",
    name: "윈드스톰 리저브 카베르네 소비뇽 2021",
    englishName: "Windstorm Reserve Cabernet Sauvignon",
    price: 46000,
    order: 15,
  },
  {
    id: "red-4",
    category: "음료",
    section: "redWine",
    name: "아이리스 말벡 2024",
    englishName: "Iris Malbec",
    price: 37000,
    order: 16,
  },

  // 하우스 와인
  {
    id: "house-wine-1",
    category: "음료",
    section: "houseWine",
    name: "HOUSE WINE",
    bottlePrice: 32000,
    glassPrice: 8000,
    order: 17,
  },

  // 맥주
  {
    id: "beer-featured-1",
    category: "음료",
    section: "beerFeatured",
    name: "생맥주",
    description: "Draft Beer",
    price: 3500,
    image: "images/menu/beer.png",
    order: 18,
  },
  {
    id: "beer-1",
    category: "음료",
    section: "beer",
    name: "스텔라 아르투아",
    description: "Bottle Beer",
    price: 7000,
    image: "",
    order: 19,
  },
  ];