export const menuItems = [
  {
    id: 1,
    name: "화이트 라구 딸리아뗄레",
    category: "시그니처",
    price: "28,000",
    description: "진한 육향과 부드러운 소스가 살아있는 생면 파스타",
    tags: ["생면", "시그니처"],
    image: "",
    featured: true,
  },
  {
    id: 2,
    name: "버섯크림 리가토니",
    category: "파스타",
    price: "26,000",
    description: "버섯 향과 크림의 밸런스를 살린 진한 스타일",
    tags: ["크림", "추천"],
    image: "",
    featured: true,
  },
  {
    id: 3,
    name: "꼬모 피자",
    category: "피자",
    price: "23,000",
    description: "화덕 느낌의 비주얼과 바삭한 식감을 살린 대표 피자",
    tags: ["베스트", "공유"],
    image: "",
    featured: true,
  },
  {
    id: 4,
    name: "와인안주 플레이트",
    category: "전채/와인안주",
    price: "19,000",
    description: "와인과 같이 즐기기 좋은 가벼운 전채 구성",
    tags: ["와인안주", "라이트"],
    image: "/menu/burata cheese.jpg",
    featured: false,
  },
  {
    id: 5,
    name: "제철 메뉴 예시",
    category: "시즌/변동",
    price: "27,000",
    description: "계절 식재료를 활용한 이번 주 추천 메뉴",
    tags: ["제철", "한정"],
    image: "",
    featured: false,
  },
  {
    id: 6,
    name: "2인 쉐어 코스",
    category: "프로모션",
    price: "59,000",
    description: "처음 방문한 손님이 꼬모를 쉽게 경험할 수 있는 구성",
    tags: ["쉐어", "추천"],
    image: "",
    featured: false,
  },
];

export const categories = [
  "전체",
  "시그니처",
  "파스타",
  "피자",
  "전채/와인안주",
  "시즌/변동",
  "프로모션",
];