export const categoryOrder = [
  "생면파스타",
  "피자 · 리조또 · 메인",
  "에피타이저 · 디저트",
  "논알콜음료",
  "주류",
];

export const menuData = [
  // 생면파스타
  {
    id: "pasta-1",
    category: "생면파스타",
    name: "마늘새우 스파게티",
    description: "구운마늘 페이스트를 이용한 파스타",
    price: 18000,
    image: "/images/menu/Shrimp-Garlic-Spaghetti.png",
    badges: ["시그니처"],
    featured: false,
    order: 1,
  },
  {
    id: "pasta-2",
    category: "생면파스타",
    name: "토마토 스파게티",
    description: "깔끔하고 산뜻한 토마토 베이스 스파게티",
    price: 16000,
    image: "/images/menu/tomato-spaghetti.png",
    badges: [],
    featured: false,
    order: 2,
  },
  {
    id: "pasta-3",
    category: "생면파스타",
    name: "버섯크림 리가토니",
    description: "진한 버섯 풍미와 고소한 크림의 리가토니",
    price: 17000,
    image: "/images/menu/Mushroom-Cream-Rigatoni.png",
    badges: ["인기"],
    featured: true,
    order: 3,
  },
  {
    id: "pasta-4",
    category: "생면파스타",
    name: "비스크 새우 딸리아뗄레",
    description: "새우 비스크의 깊은 풍미를 살린 딸리아뗄레",
    price: 23000,
    image: "/images/menu/Bisque shrimp tagliatelle.png",
    badges: [],
    featured: false,
    order: 4,
  },
  {
    id: "pasta-5",
    category: "생면파스타",
    name: "구운당근 크림 뇨끼",
    description: "부드러운 당근 풍미와 피스타치오의 고소함",
    price: 18000,
    image: "/images/menu/Roasted Carrot Cream Gnocchi.png",
    badges: [],
    featured: false,
    order: 5,
  },
  {
    id: "pasta-6",
    category: "생면파스타",
    name: "포르치니 버섯 뇨끼",
    description: "포르치니 향을 살린 진한 버섯 뇨끼",
    price: 21000,
    image: "/images/menu/Porcini gnocchi.png",
    badges: [],
    featured: false,
    order: 6,
  },
  {
    id: "pasta-7",
    category: "생면파스타",
    name: "화이트라구 딸리아뗄레",
    description: "부드럽고 깊은 풍미의 화이트라구 딸리아뗄레",
    price: 19000,
    image: "/images/menu/White ragu tagliatelle.png",
    badges: ["인기"],
    featured: false,
    order: 7,
  },
  {
  id: "pasta-8",
  category: "생면파스타",
  name: "바질페스토 스파게티",
  description: "바질의 향긋함과 고소함이 살아있는 스파게티",
  price: 18000,
  image: "/images/menu/Basil Pesto Spaghetti.png",
  badges: [],
  featured: false,
  order: 8,
},

  // 피자 · 리조또 · 메인
  {
    id: "main-1",
    category: "피자 · 리조또 · 메인",
    name: "채끝등심 버섯 리조또",
    description: "채끝등심과 버섯의 풍미를 담은 리조또",
    price: 26000,
    image: "/images/menu/Sirloin mushroom risotto.png",
    badges: [],
    featured: false,
    order: 1,
  },
  {
    id: "main-2",
    category: "피자 · 리조또 · 메인",
    name: "먹물관자 리조또",
    description: "먹물의 감칠맛과 관자의 풍미를 살린 리조또",
    price: 20000,
    image: "/images/menu/Squid-ink-scallop-risotto.png",
    badges: [],
    featured: false,
    order: 2,
  },
  {
    id: "main-3",
    category: "피자 · 리조또 · 메인",
    name: "가리비관자피자",
    description: "관자의 풍미를 살린 꼬모 대표 피자",
    price: 21000,
    image: "/images/menu/Scallop pizza.png",
    badges: ["시그니처"],
    featured: true,
    order: 3,
  },
  {
    id: "main-4",
    category: "피자 · 리조또 · 메인",
    name: "리코타 고르곤졸라 피자",
    description: "리코타의 부드러움과 고르곤졸라의 풍미",
    price: 17000,
    image: "/images/menu/Ricotta-Gorgonzola-pizza.png",
    badges: ["인기"],
    featured: false,
    order: 4,
  },
  {
    id: "main-5",
    category: "피자 · 리조또 · 메인",
    name: "마르게리따 피자",
    description: "토마토, 치즈, 바질의 클래식 피자",
    price: 15000,
    image: "/images/menu/Margherita.png",
    badges: [],
    featured: false,
    order: 5,
  },
  {
    id: "main-6",
    category: "피자 · 리조또 · 메인",
    name: "채끝등심 250g",
    description: "담백하게 구운 채끝등심 스테이크",
    price: 47000,
    image: "/images/menu/Striploin Steak.png",
    badges: ["메인"],
    featured: false,
    order: 6,
  },

  // 에피타이저 · 디저트
{
  id: "side-1",
  category: "에피타이저 · 디저트",
  name: "부라타치즈",
  description: "부드럽고 신선한 부라타치즈",
  price: 17000,
  image: "/images/menu/burata-cheese.jpg",
  badges: ["추천"],
  featured: false,
  order: 1,
},
{
  id: "side-2",
  category: "에피타이저 · 디저트",
  name: "리코타치즈샐러드",
  description: "가볍게 즐기기 좋은 리코타치즈 샐러드",
  price: 15000,
  image: "/images/menu/Ricotta cheese salad.png",
  badges: ["시그니처"],
  featured: false,
  order: 2,
},
{
  id: "side-3",
  category: "에피타이저 · 디저트",
  name: "트러플감자튀김",
  description: "트러플 향을 더한 감자튀김",
  price: 10000,
  image: "",
  badges: ["추천"],
  featured: false,
  order: 3,
},
{
  id: "side-4",
  category: "에피타이저 · 디저트",
  name: "빵추가 3피스",
  description: "소스와 함께 곁들이기 좋은 빵 추가",
  price: 5000,
  image: "",
  badges: [],
  featured: false,
  order: 4,
},
{
  id: "side-5",
  category: "에피타이저 · 디저트",
  name: "오늘의 디저트",
  description: "당일 준비된 디저트",
  price: 5000,
  image: "",
  badges: [],
  featured: false,
  order: 5,
},

  // 논알콜음료
  // 아직 메뉴 없음

  // 주류
  // 아직 메뉴 없음
];